name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: running test coverage
      run: cargo tarpaulin | tail -n 1 | awk -F% '{print;} $1 + 0 < 10 {exit 1}'
